### ISSUE TITLE
Support for displaying events

### ISSUE THREAD

**Issue by yglodt** [mpachnis/mp-calendar#2]
It would be nice if mp-calendar could display events , e.g. from a json datasource.

**Comment by mpachnis** [comment]
It's the next feature I want to add, hopefully by the end of the month.

**Comment by mpachnis** [comment]
Event support is added. 
There are 4 event categories:  red, blue, green and yellow.
Create an event.json file, include the `events-data="event.json"` to the calendar element and that's it. There will be a small colored line on the date based on the class.

event.json structure
```
[
    {
        "title": "Red category",
        "content": "Skype call at 15:40",
        "date": "2017-05-04",
        "class": "red"
    }
]
```
