### ISSUE TITLE
api for mp-calendar?

### ISSUE THREAD

**Issue by ghost** [mpachnis/mp-calendar#23]
Hi all.

I was thinking of developing an api for mp-calendar. *What do you all think of the idea?*

#### 1.1 POST in 'https://mp.calendar.io/component?'  
```markdown
https://mp.calendar.io/component?id='1'&title='title'&content='content'&date='date'&color='color'
```

#### 1.1.2 return json

```json
[
    {
        "title": "Skype",
        "content": "Skype call at 15:40",
        "date": "2017-06-02",
        "color": "#000"
    }
]
```

#### 1.2 GET in 'https://mp.calendar.io/component?'  
```markdown
https://mp.calendar.io/component?id='1'&title='title'&content='content'&date='date'&color='color'
```

#### 1.2.1 return json

```json
[
    {
        "title": "Skype",
        "content": "Skype call at 15:40",
        "date": "2017-06-02",
        "color": "#000"
    }
]
```

**Comment by mpachnis** [comment]
Hi @codehangen not sure why you need to do this as it's very simply as is. 

Nevertheless, in my opinion you don't need to use query string parameters.
You also need to think how are you planning to load the event(s), all at once, per month, per day. Off course you will need to update the component to support what you want.

**Comment by ghost** [comment]
Hi mpachnis.

> Hi @codehangen not sure why you need to do this as it's very simply as is.
> Nevertheless, in my opinion you don't need to use query string parameters.
You also need to think how are you planning to load the event(s), all at once, per month, per day. Off course you will need to update the component to support what you want.

thank you for feedback.
