### ISSUE TITLE
Events Display 

### ISSUE THREAD

**Issue by cappittall** [mpachnis/mp-calendar#5]
First of all, thank you for the very nice component. I have a small issue. When I add an event, this events is not shows at calendar unless I reload. And second is events has some display problem at small screen ( like on phone) (see attached photo )
Actually, I have solved with adding some extra code to your component, but this is not the good way I think :) 

Thank you in advance!

![screenshot 22](https://user-images.githubusercontent.com/14778803/41617313-d3ca89e4-7408-11e8-95a3-5cba6008ca19.png)

**Comment by mpachnis** [comment]
Hi, can u share a live example?  You're adding the `event-file` property with the .json file and you don't see the events the first time the element was rendered?  On what mobile do u see the events to be out of the screen?

**Comment by cappittall** [comment]
I can add the evet file and events are displayed.(i use firebase database rest api.) There is no problem with that. But after when i added an event more. Need to re-load json file. (For this i added a small code in your component.) 
I use samsung j7 mobile. And you may see the live demo web.visitsapp.com

**Comment by mpachnis** [comment]
I push another branch 'events' can you clone this one and check it. I have added a new property `event-object` which you can add an object instead of json file. I also add observers on each one so everytime tha .json file or the object changes will fire an event to load the data.

**Comment by cappittall** [comment]
Thank for your effort. I will check it. Also keep in mind, that this mp-calendar shows on with paper-dialog element.

**Comment by cappittall** [comment]
This `events-object`  (not event-object) working quite good.  Also, this time I don't know why, the events visible better :) Thank you very much.

**Comment by mpachnis** [comment]
Nice to hear that. I’ll merge the branches in the next 10 days.
