### ISSUE TITLE
Can you give support for Polymer 3 witn NPM

### ISSUE THREAD

**Issue by umamaheshbhamidipati** [mpachnis/mp-calendar#9]
Hi Mpachnis,

Can you please provide support for polymer 3 with npm

**Comment by mpachnis** [comment]
Hi Uma Mahesh,

I'll try to push it by the end of week.

**Comment by umamaheshbhamidipati** [comment]
Thanks!

**Comment by mpachnis** [comment]
I push a new branch 3.x. Feel free to try it until I merge it to master, npm i mpachnis/mp-calendar#3.x --save

**Comment by umamaheshbhamidipati** [comment]
Thank you so much :)
